# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8561a33167a560276e0137c5839b9aae1a9a5a6d8fb8518dc86e1aa4ca6980245d95a1b9497a347cea958cc5a3df15afa9d413cf141429d6f384cd4f29430615

test:
  secret_key_base: 40464a1ceda7f7e789fc287e58329f6b921b803fb73ca59808cfc375adfbb1b8dc520ab2c4f8dee14d4f83645e009ae950ead9d130f34a3869e35dd416ff0eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
